services:
  - name: web
    instance_count: 4
    instance_size_slug: professional-xxl
    routes:
      - path: /
    git:
      repo: "https://github.com/Haris00123/restaurant_rep_flask"
      branch: master
    build_command: "go build ./"
    run_command: "gunicorn -c gunicorn_config.py wsgi:app"
    envs:
    - key: BUILD_ONLY_VAR
      scope: BUILD_TIME
      value: hello world
    - key: RUNTIME_ONLY_VAR
      scope: RUN_TIME
      value: i'm a little teapot